config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, except: [:destroy] do
    resources :horses
    resources :charges, only: [:index, :show]
    resources :events, only: [:index, :show]
    resources :events, only: [:index, :show]
    resources :notes, only: [:index, :show]
  end

  resources :horses do
    resources :users, only: [:show]
    resources :charges, except: [:index, :show]
    resources :events, except: [:index, :show]
    resources :veternarians, only: [:show]
    resources :farriers, only: [:show]
    resources :notes, only: [:index, :show]
  end

  resources :farriers
  resources :veterinarians
  resources :notes
  resources :charges
  resources :events

  root 'users#new'
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :horse
  validates :text, presence: true, length: { minimum: 10, maximum: 2000 }
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authorize_user, except: [:show]
  def show
    @note = Note.find(params[:id])
    @horse = @note.horse
  end

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)
    if @note.save
      flash[:notice] = "New Note Added!"
      redirect_to @note
    else
      flash[:alert] = "New Note Not Created"
      render :new
    end
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
   @note = Note.find(params[:id])
   if @note.update_attributes(note_params)
     flash[:notice] = "Note Updated!"
     redirect_to @note
   else
     render 'edit'
   end
 end

  def destroy
    @note = Note.find(params[:id])

    if @note.destroy
      flash[:notice] = 'Note has been deleted.'
      redirect_to new_note_path
    end
  end

  private

  def note_params
    params.require(:note).permit(
      :text,
      :horse_id
    )
  end

  def authorize_user
    if !user_signed_in? || !current_user.admin?
      raise ActionController::RoutingError.new("Not Found")
    end
  end
end

app/views/notes/edit.html.erb
<br></br>
<%= simple_form_for @note do |f| %>
<% if @note.errors.any? %>
<div id="error_explanation-note">
        <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

        <ul>
        <% @note.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
<div class="row">
  <div class="small-6 large-centered columns">
    <div class="form-inputs">
      <h1 class="form_header">Edit Note</h1>
      <%= f.label :horse_id, 'Horse', class: 'form-actions' %>
      <%= f.select :horse_id, Horse.all.collect { |h| [h.barn_name, h.id] } %>
      <%= f.label :text, 'Enter Note', class: 'form-actions' %>
      <%= f.text_area :text %>
      <div class="form-actions">
        <%= f.button :submit, 'Update' %>
        <p><%= link_to "Delete Note", note_path(@note.id), data: { confirm: "Are you sure?" }, method: :delete %> <br />
          <%= link_to "Back", :back, class: 'link' %></p>
        </div>
    </div>
  </div>
    <% end %>
  </div>

app/views/notes/new.html.erb
<br></br>
<%= simple_form_for @note do |f| %>
<% if @note.errors.any? %>
<div id="error_explanation-note">
        <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

        <ul>
        <% @note.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
<div class="row">
  <div class="small-6 large-centered columns">
    <div class="form-inputs">
      <h1 class="form_header">Add New Note</h1>
      <%= f.label :horse_id, 'Horse', class: 'form-actions' %>
      <%= f.select :horse_id, Horse.all.collect { |h| [h.barn_name, h.id] } %>
      <%= f.label :text, 'Enter Note', class: 'form-actions' %>
      <%= f.text_area :text %>
      <div class="form-actions">
        <%= f.button :submit, 'Submit' %>
        <p><%= link_to "Back", :back, class: 'link' %> <br />
          <%= link_to 'Home', user_path(current_user) %></p>
        </div>
    </div>
  </div>
    <% end %>
  </div>

app/views/notes/show.html.erb
<br />
<div class="row">
  <div class="small-6 large-centered columns">
    <div class='note_info'>
      <h1 class='note_data'><%= @note.created_at.strftime("%b. %d, %Y") %></h1>
      <h2 class='note_header'><%= @note.horse.barn_name  %><h2>
      <h3 class='note_data'><%= @note.text %></h3>
      <% if current_user.admin? %>
        <%= link_to 'Edit', edit_note_path(params[:id]) %> <br />
        <%= link_to 'Back to Horse', horse_path(@note.horse_id) %>
      <% end %>
    </div>
  </div>
</div