config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, except: [:destroy] do
    resources :horses
    resources :charges, only: [:index, :show]
    resources :events, only: [:index, :show]
    resources :events, only: [:index, :show]
    resources :notes, only: [:index, :show]
  end

  resources :horses do
    resources :users, only: [:show]
    resources :charges, except: [:index, :show]
    resources :events, except: [:index, :show]
    resources :veternarians, only: [:show]
    resources :farriers, only: [:show]
    resources :notes, only: [:index, :show]
  end

  resources :farriers
  resources :veterinarians
  resources :notes
  resources :charges
  resources :events

  root 'users#new'
end

app/controllers/horses_controller.rb
class HorsesController < ApplicationController
  before_action :authorize_user, except: [:show]
  def show
    @horse = Horse.find(params[:id])
    @user = @horse.user
    @veterinarian = @horse.veterinarian
    @farriers = @horse.farrier
    @charges = Charge.all
    @events = Event.all
    @notes = Note.all
  end

  def new
    @horse = Horse.new
  end

  def create
    @horse = Horse.new(horse_params)
    if @horse.save
      flash[:notice] = "New Horse Added!"
      redirect_to @horse
    else
      flash[:alert] = "New Horse Not Created"
      render :new
    end
  end

  def edit
    @horse = Horse.find(params[:id])
  end

  def update
   @horse = Horse.find(params[:id])
   if @horse.update_attributes(horse_params)
     flash[:notice] = "Horse Updated!"
     redirect_to @horse
   else
     render 'edit'
   end
 end

  def destroy
    @horse = Horse.find(params[:id])

    if @horse.destroy
      flash[:notice] = 'Horse has been deleted.'
      redirect_to new_horse_path
    end
  end

  private

  def horse_params
    params.require(:horse).permit(
      :registered_name,
      :barn_name,
      :discipline,
      :breed,
      :picture,
      :user_id,
      :veterinarian_id,
      :farrier_id
    )
  end

  def authorize_user
    if !user_signed_in? || !current_user.admin?
      raise ActionController::RoutingError.new("Not Found")
    end
  end
end

app/views/horses/edit.html.erb
<div class='wrapper'>
<%= simple_form_for @horse do |f| %>
<% if @horse.errors.any? %>
<div id="error_explanation-horse">
        <h2><%= pluralize(@horse.errors.count, "error") %> prohibited this horse from being saved:</h2>

        <ul>
        <% @horse.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
<div class="row">
  <div class="small-6 large-centered columns">
    <div class="form-inputs">
      <h1 class="form_header">Edit <%= @horse.barn_name %></h1>
      <%= f.input :registered_name, label: 'Registered Name' %>
      <%= f.input :barn_name, label: 'Barn Name', required: true, autofocus: true %>
      <%= f.input :breed, label: 'Breed', required: true, autofocus: true %>
      <%= f.input :discipline, label: 'Discipline', autofocus: true %>
      <%= f.label :user_id, 'Owner' %>
      <%= f.select :user_id, User.all.collect { |p| [p.name, p.id] }, autofocus: true %>
      <%= f.label :veterinarian_id, 'Veterinarian' %>
      <%= f.select :veterinarian_id, Veterinarian.all.collect { |v| [v.name, v.id] }, autofocus: true %>
      <%= f.label :farrier_id, 'Farrier' %>
      <%= f.select :farrier_id, Farrier.all.collect { |f| [f.name, f.id] }, autofocus: true %>
      <%= f.input :picture, type: :file %>
      <div class="form-actions">
        <%= f.button :submit, 'Update' %>
        <p><%= link_to "Delete Horse", horse_path(@horse.id), data: { confirm: "Are you sure?" }, method: :delete %> <br />
          <%= link_to "Back", :back, class: 'link' %></p>
        </div>
    </div>
    <% end %>
  </div>
</div>
</div>

app/views/horses/new.html.erb
<div class='wrapper'>
<%= simple_form_for @horse do |f| %>
<% if @horse.errors.any? %>
<div id="error_explanation-horse">
        <h2><%= pluralize(@horse.errors.count, "error") %> prohibited this horse from being saved:</h2>

        <ul>
        <% @horse.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
<div class="row">
  <div class="small-6 large-centered columns">
    <div class="form-inputs">
      <h1 class="form_header">Add New Horse</h1>
      <%= f.label :registered_name, 'Registered Name', class: 'form-actions' %>
      <%= f.input :registered_name %>
      <%= f.label :barn_name, 'Barn Name', class: 'form-actions' %>
      <%= f.input :barn_name, required: true %>
      <%= f.label :breed, 'Breed', class: 'form-actions' %>
      <%= f.input :breed, required: true %>
      <%= f.label :discipline, 'Discipline', class: 'form-actions' %>
      <%= f.input :discipline %>
      <%= f.label :user_id, 'Owner', class: 'form-actions' %>
      <%= f.select :user_id, User.all.collect { |p| [p.name, p.id] } %>
      <%= f.label :veterinarian_id, 'Veterinarian', class: 'form-actions' %>
      <%= f.select :veterinarian_id, Veterinarian.all.collect { |v| [v.name, v.id] } %>
      <%= f.label :farrier_id, 'Farrier', class: 'form-actions' %>
      <%= f.select :farrier_id, Farrier.all.collect { |f| [f.name, f.id] } %>
      <%= f.input :picture, type: :file, class: 'form-actions' %>
      <div class="form-actions">
        <%= f.button :submit, 'Submit' %>
        <p><%= link_to "Back", :back, class: 'link' %> <br />
          <%= link_to 'Home', user_path(current_user) %></p>
        </div>
        <% end %>
    </div>
  </div>
</div>
</div>

app/views/horses/show.html.erb
<div class='wrapper'>
<% if user_signed_in? %>
  <div class="row">
    <div class="small-6 columns">
      <img class="picture" <%= image_tag @horse.picture %>
    </div>
    <br></br>
    <br></br>
      <div class="small-6 columns">
        <div class='info_tile' >
          <br></br>
          <h1 class='registered_name'><%= @horse.registered_name %></h1>
          <h1 class='horse_name'><%= @horse.barn_name %></h1>
          <h5 class='user_name'> Owner: <%= @horse.user.name %></h5>
          <div class="list_items">
          <p>Breed: <%= @horse.breed %><br />
          Discipline: <%= @horse.discipline %><br />
          Veterinarian: <%= link_to @horse.veterinarian.name, veterinarian_path(@horse.veterinarian.id)%><br />
          Farrier: <%= link_to @horse.farrier.name, farrier_path(@horse.farrier.id) %></p>
          <% end %>
          <% if current_user.admin? %>
          <%= link_to 'Edit', edit_horse_path(params[:id]) %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <br></br>
  <div class="row">
    <div class="small-6 columns">
      <div class='charges'>
        <h3 class='charges_head'>Charges</h3>
        <% @charges.each do |c| %>
          <% if c.horse.id === @horse.id %>
            <a href= <%= charge_path(c.id) %>
            <p><%= c.date.strftime("%B %d, %Y") %>: <%= c.description %>: $<%= c.amount %></p>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="small-6 columns">
      <div class='events'>
        <h3 class='events_head'>Events</h3>
        <% @events.each do |e| %>
          <% if e.horse.id === @horse.id %>
            <a href= <%= event_path(e.id) %>
            <p><%= e.date.strftime("%B %d, %Y") %> <%= e.time %> <%= e.description %></p>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="large-10 large-centered columns">
      <div class='notes'>
        <h3 class='notes_head'>Notes</h3>
          <% @notes.each do |n| %>
            <a href= <%= note_path(n.id) %>
            <% if n.horse.id === @horse.id %>
              <p><%= n.created_at.strftime("%b. %d, %Y") %> <%= n.text %></p>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
</div>