config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, except: [:destroy] do
    resources :horses
    resources :charges, only: [:index, :show]
    resources :events, only: [:index, :show]
    resources :events, only: [:index, :show]
    resources :notes, only: [:index, :show]
  end

  resources :horses do
    resources :users, only: [:show]
    resources :charges, except: [:index, :show]
    resources :events, except: [:index, :show]
    resources :veternarians, only: [:show]
    resources :farriers, only: [:show]
    resources :notes, only: [:index, :show]
  end

  resources :farriers
  resources :veterinarians
  resources :notes
  resources :charges
  resources :events

  root 'users#new'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :horses

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create
  validates :phone_number, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip_code, presence: true, numericality: true

  def admin?
    role == "admin"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @horse = Horse.all
    @charges = Charge.all
    @events = Event.all
    @notes = Note.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'Account was successfully created'
      redirect_to current_user_path
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])

    if @user.destroy
      flash[:notice] = 'User has been deleted.'
      redirect_to new_user_path
    end
  end
end

app/views/users/new.html.erb
<br />
<div class="small-3 small-centered columns">
    <div class="card">
      <% if user_signed_in? %>
        <h2 class="nav_buttons"> <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %> </h2>
        <h2 class="nav_buttons"> <%= link_to 'Edit Account', edit_user_registration_path %></h2>
        <h2 class="nav_buttons"> <%= link_to 'Owner Info', user_path(current_user) %>
      <% else %>
      <div class='large-6 large-centered columns'>
        <h2 class="nav_buttons"><%= link_to 'Sign In', new_user_session_path %></h2>
        <h2 class="nav_buttons"><%= link_to 'Sign Up', new_user_registration_path %></h2>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% if user_signed_in? %>
  <br></br>
  <br></br>
  <div class='wrapper'>
  <div class="row">
    <div class="small-6 columns">
      <div class='user_info'>
        <h1 class='user'><%= @user.name %></h1>
        <p><%= @user.email %><br />
        <%= @user.phone_number %><br />
        <%= @user.address %> <br />
        <%= @user.city %>, <%= @user.state %> <%= @user.zip_code %></p>
      </div>
    </div>
      <% if current_user.admin? %>
    <div class="small-6 columns">
      <div class='horse_list'>
        <h2 class='horse'>Horses</h2>
        <% @horse.each do |h| %>
          <a href=<%= horse_path(h.id) %>>
          <h3 class='horses'><%= h.barn_name %></h3>
          <% end %>
        </div>
      </div>
    </div>
      <br />
      <br />
      <div class="row">
        <div class="medium-3 columns">
          <a href=<%= new_horse_path %>>
            <div class="callout">
              <h2 class="nav_buttons">Add New Horse</h2>
            </div>
          </a>
        </div>
          <div class="medium-3 columns">
            <a href= <%= new_charge_path %>>
              <div class="callout">
                <h2 class="nav_buttons">Add New Charge</h2>
              </div>
            </a>
          </div>
          <div class="medium-3 columns">
            <a href= <%= new_event_path %>>
              <div class="callout">
                <h2 class="nav_buttons">Add New Event</h2>
              </div>
            </a>
          </div>
          <div class="medium-3 columns">
            <a href= <%= new_note_path %>>
              <div class="callout">
                <h2 class="nav_buttons">Add New Note</h2>
              </div>
            </a>
          </div>
        </div>
        <div class="row">
          <div class="medium-3 columns">
            <a href= <%= veterinarians_path %>>
              <div class="callout">
                <h2 class="nav_buttons">Veterinarian List</h2>
              </div>
            </a>
          </div>
          <div class="medium-3 columns">
            <a href= <%= new_veterinarian_path %>>
              <div class="callout">
                <h2 class="nav_buttons">Add New Veterinarian</h2>
              </div>
            </a>
          </div>
          <div class="medium-3 columns">
            <a href= <%= farriers_path %>>
              <div class="callout">
                <h2 class="nav_buttons">Farrier List</h2>
              </div>
            </a>
          </div>
          <div class="medium-3 columns">
            <a href= <%= new_farrier_path %>>
              <div class="callout">
                <h2 class="nav_buttons">Add New Farrier</h2>
              </div>
            </a>
          </div>
        </div>
    <% else %>
    <div class="small-6 columns">
      <div class='horse_list'>
        <h2 class='horse'>Horses</h2>
        <% @horse.each do |h| %>
        <a href=<%= horse_path(h.id) %>>
          <% if h.user.id === @user.id %>
          <div class='callout'>
            <h3 class='horses'><%= h.barn_name %></h3>
          </div>
          <% end %>
        </a>
        <% end %>
      </div>
    </div>
  </div>
  <br></br>
  <div class="row">
    <div class="small-6 columns">
      <div class='charges'>
        <h3 class='charges_head'>Charges</h3>
        <% @horse.each do |h| %>
          <% if h.user.id === @user.id %>
            <% @charges.each do |c| %>
              <% if c.horse.id === h.id %>
                <a href= <%= charge_path(c.id) %>
                <p><%= c.date.strftime("%B %d, %Y") %> <%= c.description %> <%= c.amount %>-<%= h.barn_name %></p>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="small-6 columns">
      <div class='events'>
        <h3 class='events_head'>Events</h3>
        <% @horse.each do |h| %>
          <% if h.user.id === @user.id %>
            <% @events.each do |e| %>
              <a href= <%= event_path(e.id) %>
              <% if e.horse.id === h.id %>
                <p><%= e.date.strftime("%B %d, %Y") %> at <%= e.time %> <%= e.description %>-<%= h.barn_name %></p>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
  <div class='row>'>
    <div class='large-6 large-centered columns'>
      <div class='notes'>
        <h3 class='notes_head'>Notes</h3>
        <% @horse.each do |h| %>
          <% if h.user.id === @user.id %>
            <% @notes.each do |n| %>
              <a href= <%= note_path(n.id) %>
              <% if n.horse.id === h.id %>
                <p><%= n.created_at.strftime("%b. %d, %Y") %>-<%= h.barn_name %></p>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
<% end %>
</div>