config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, except: [:destroy] do
    resources :horses
    resources :charges, only: [:index, :show]
    resources :events, only: [:index, :show]
    resources :events, only: [:index, :show]
    resources :notes, only: [:index, :show]
  end

  resources :horses do
    resources :users, only: [:show]
    resources :charges, except: [:index, :show]
    resources :events, except: [:index, :show]
    resources :veternarians, only: [:show]
    resources :farriers, only: [:show]
    resources :notes, only: [:index, :show]
  end

  resources :farriers
  resources :veterinarians
  resources :notes
  resources :charges
  resources :events

  root 'users#new'
end

app/models/charge.rb
class Charge < ApplicationRecord
  belongs_to :horse

  validates :date, presence: true
  validates :description, presence: true
  validates :amount, presence: true, numericality: true
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :authorize_user, except: [:show]
  def show
    @charge = Charge.find(params[:id])
    @horse = @charge.horse
  end

  def new
    @charge = Charge.new
  end

  def create
    @charge = Charge.new(charge_params)
    if @charge.save
      flash[:notice] = "New Charge Added!"
      redirect_to @charge
    else
      flash[:alert] = "New Charge Not Created"
      render :new
    end
  end

  def edit
    @charge = Charge.find(params[:id])
  end

  def update
   @charge = Charge.find(params[:id])
   if @charge.update_attributes(charge_params)
     flash[:notice] = "Charge Updated!"
     redirect_to @charge
   else
     render 'edit'
   end
 end

  def destroy
    @charge = Charge.find(params[:id])

    if @charge.destroy
      flash[:notice] = 'Charge has been deleted.'
      redirect_to new_charge_path
    end
  end

  private

  def charge_params
    params.require(:charge).permit(
      :date,
      :description,
      :amount,
      :horse_id
    )
  end

  def authorize_user
    if !user_signed_in? || !current_user.admin?
      raise ActionController::RoutingError.new("Not Found")
    end
  end
end

app/views/charges/edit.html.erb
<div class='wrapper'>
<br></br>
<%= simple_form_for @charge do |f| %>
<% if @charge.errors.any? %>
<div id="error_explanation-charge">
        <h2><%= pluralize(@charge.errors.count, "error") %> prohibited this charge from being saved:</h2>

        <ul>
        <% @charge.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
<div class="row">
  <div class="small-6 large-centered columns">
    <div class="form-inputs">
      <h1 class="form_header">Edit Charge</h1>
      <%= f.label :horse_id, 'Horse', class: 'form-actions' %>
      <%= f.select :horse_id, Horse.all.collect { |h| [h.barn_name, h.id] } %>
      <%= f.label :date, 'Due Date', class: 'form-actions' %>
      <%= f.date_select('date',
          options = { start_year: 2017, order: [:month, :day, :year]},
          html_options = { class: 'select-date'})  %>
      <%= f.label :amount, 'Amount', class: 'form-actions' %>
      <%= f.input :amount %>
      <%= f.label :description, 'Description', class: 'form-actions' %>
      <%= f.input :description %>
      <div class="form-actions">
        <%= f.button :submit, 'Update' %>
        <p><%= link_to "Delete Charge", charge_path(@charge.id), data: { confirm: "Are you sure?" }, method: :delete %><br />
          <%= link_to "Back", :back, class: 'link' %></p>
        </div>
    </div>
  </div>
    <% end %>
  </div>
</div>

app/views/charges/new.html.erb
<div class='wrapper'>
<br></br>
<%= simple_form_for @charge do |f| %>
<% if @charge.errors.any? %>
<div id="error_explanation-charge">
        <h2><%= pluralize(@charge.errors.count, "error") %> prohibited this charge from being saved:</h2>

        <ul>
        <% @charge.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
<div class="row">
  <div class="small-6 large-centered columns">
    <div class="form-inputs">
      <h1 class="form_header">Add New Charge</h1>
      <%= f.label :horse_id, 'Horse', class: 'form-actions' %>
      <%= f.select :horse_id, Horse.all.collect { |h| [h.barn_name, h.id] } %>
      <%= f.label :date, 'Due Date', class: 'form-actions' %>
      <%= f.date_select('date',
          options = { start_year: 2017, order: [:month, :day, :year]},
          html_options = { class: 'select-date'})  %>
      <%= f.label :amount, 'Amount', class: 'form-actions' %>
      <%= f.input :amount %>
      <%= f.label :description, 'Description', class: 'form-actions' %>
      <%= f.input :description %>
      <div class="form-actions">
        <%= f.button :submit, 'Submit' %>
        <p><%= link_to "Back", :back, class: 'link' %><br />
          <%= link_to 'Home', user_path(current_user) %></p>
        </div>
    </div>
  </div>
    <% end %>
  </div>
</div>

app/views/charges/show.html.erb
  <br></br>
  <div class='wrapper'>
  <div class="row">
    <div class="small-6 large-centered columns">
      <div class='charge_info'>
        <h1 class='charge_header'>For: <%= @charge.horse.barn_name%><h1>
          <h3 class='charge_data'>Amount Due: $<%= @charge.amount%></h3>
          <h3 class='charge_data'>Due: <%= @charge.date.strftime("%B %d, %Y")%></h3>
        <h3 class='charge_data'>Description: <%= @charge.description %></h3>
        <% if current_user.admin? %>
          <%= link_to 'Edit', edit_charge_path(params[:id]) %> <br />
          <%= link_to 'Back to Horse', horse_path(@charge.horse_id) %>
        <% end %>
      </div>
    </div>
  </div
</div>